
-injars "C:\Users\EFSEEa\Documents\GitHub\SBGames\public\sbg-bootstrap.jar"
-outjars "C:\Users\EFSEEa\Documents\GitHub\SBGames\public\sbg-bootstrap-obf.jar"
-libraryjars "C:\Program Files\Eclipse Adoptium\jdk-17.0.18.8-hotspot\jmods\java.base.jmod"

-dontwarn **

-optimizationpasses 5
-allowaccessmodification
-repackageclasses 'com.sbgames.bootstrap.obf'

-classobfuscationdictionary "C:\Users\EFSEEa\Documents\GitHub\SBGames\scratch\obf_dict.txt"
-obfuscationdictionary "C:\Users\EFSEEa\Documents\GitHub\SBGames\scratch\obf_dict.txt"
-useuniqueclassmembernames

-keep public class com.sbgames.bootstrap.SBGBootstrap {
    public static void main(java.lang.String[]);
}
-keepattributes Signature,InnerClasses,EnclosingMethod
